/*
 * Copyright MalchroSoft - Aymeric MALCHROWICZ. All right reserved.
 * The source code that contains this comment is an intellectual property
 * of MalchroSoft [Aymeric MALCHROWICZ]. Use is subject to licence terms.
 */
package com.malchrosoft.cammerger.test.barcodescanner;

import java.awt.Canvas;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.image.BufferStrategy;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author aymeric
 */
public class BarcodeScannerFrame extends javax.swing.JFrame
{
	private BufferStrategy bs;

	/** Creates new form barcodeSannerFrame */
	public BarcodeScannerFrame()
	{
		initComponents();
		this.setTitle("Code bar scanner");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 820, 740);
		this.setMinimumSize(new Dimension(800, 600));
		this.codebarModeToggleBtn.setSelected(true);

		this.init();
	}

	private void init()
	{
		this.camRenderCanvas.createBufferStrategy(4);
		this.bs = this.camRenderCanvas.getBufferStrategy();
	}

	public Graphics2D getCamRendererGraphics()
	{
		return (Graphics2D) this.bs.getDrawGraphics();
	}

	public final void redrawCamRenderer()
	{
		this.bs.show();
	}

	/** This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        toolbar = new javax.swing.JToolBar();
        codebarModeToggleBtn = new javax.swing.JToggleButton();
        canvasParentPanel = new javax.swing.JPanel();
        camRenderCanvas = new java.awt.Canvas();
        statusBar = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        scannedBarcodeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setRollover(true);
        toolbar.setMinimumSize(new java.awt.Dimension(11, 32));

        codebarModeToggleBtn.setText("Code Bar Mode");
        codebarModeToggleBtn.setFocusable(false);
        codebarModeToggleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        codebarModeToggleBtn.setName(""); // NOI18N
        codebarModeToggleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(codebarModeToggleBtn);

        getContentPane().add(toolbar, java.awt.BorderLayout.NORTH);

        canvasParentPanel.setLayout(new javax.swing.BoxLayout(canvasParentPanel, javax.swing.BoxLayout.LINE_AXIS));
        canvasParentPanel.add(camRenderCanvas);

        getContentPane().add(canvasParentPanel, java.awt.BorderLayout.CENTER);

        statusBar.setLayout(new javax.swing.BoxLayout(statusBar, javax.swing.BoxLayout.LINE_AXIS));

        statusLabel.setText("Last code : ");
        statusBar.add(statusLabel);

        scannedBarcodeLabel.setText("-");
        statusBar.add(scannedBarcodeLabel);

        getContentPane().add(statusBar, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
			javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(BarcodeScannerFrame.class.getName()).log(java.util.logging.Level.SEVERE,
				null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new BarcodeScannerFrame().setVisible(true);
			}

		});
	}

	public JLabel getScannedBarcodeLabel()
	{
		return scannedBarcodeLabel;
	}

	public Canvas getCamRenderCanvas()
	{
		return camRenderCanvas;
	}

	public JToggleButton getCodebarModeToggleBtn()
	{
		return codebarModeToggleBtn;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas camRenderCanvas;
    private javax.swing.JPanel canvasParentPanel;
    private javax.swing.JToggleButton codebarModeToggleBtn;
    private javax.swing.JLabel scannedBarcodeLabel;
    private javax.swing.JPanel statusBar;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
